// Predefined options for lawyer and law firm fields

export const LAW_SPECIALTIES = [
  // General Categories
  'Divorce',
  'Family Law',
  'Child Custody',
  'Child Support',
  'Alimony/Spousal Support',
  'Property Division',
  'Prenuptial Agreements',
  'Postnuptial Agreements',
  'Mediation',
  'Collaborative Divorce',
  'Uncontested Divorce',
  'Contested Divorce',
  'High Asset Divorce',
  'Military Divorce',
  'Same-Sex Divorce',
  'Domestic Violence',
  'Adoption',
  'Paternity',
  'Guardianship',
  'Estate Planning',
  'Elder Law',
  // Specific Practice Areas from Original Site
  'High Net Worth Divorce Cases',
  'Modifications of Custody',
  'Complex Custody Cases',
  'Modification of Child Support and Alimony',
  'Enforcement of Orders by Way of Contempt',
  'Pre and Postnuptial Agreements',
]

export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'District of Columbia' },
]

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Chinese (Mandarin)',
  'Chinese (Cantonese)',
  'Japanese',
  'Korean',
  'Arabic',
  'Hebrew',
  'Russian',
  'Polish',
  'Vietnamese',
  'Tagalog',
  'Hindi',
  'Urdu',
  'Greek',
  'Turkish',
]

export const PROFESSIONAL_MEMBERSHIPS = [
  'American Bar Association',
  'State Bar Association',
  'American Academy of Matrimonial Lawyers',
  'International Academy of Family Lawyers',
  'Association of Family and Conciliation Courts',
  'American Inns of Court',
  'National Association of Criminal Defense Lawyers',
  'American Association for Justice',
  'National Bar Association',
  'Hispanic National Bar Association',
  'Asian Pacific American Bar Association',
  'Women Lawyers Association',
]

export const CERTIFICATIONS = [
  'Board Certified Family Law',
  'Certified Divorce Financial Analyst',
  'Certified Mediator',
  'Collaborative Law Certified',
  'Certified Family Law Specialist',
  'Certified Elder Law Attorney',
]

export const FIRM_SIZES = [
  'Solo Practice',
  '2-5 Attorneys',
  '6-10 Attorneys',
  '11-25 Attorneys',
  '26-50 Attorneys',
  '51-100 Attorneys',
  '100+ Attorneys',
]

export const PRACTICE_AREAS = [
  'Divorce',
  'Family Law',
  'Child Custody',
  'Child Support',
  'Alimony',
  'Property Division',
  'Prenuptial Agreements',
  'Mediation',
  'Collaborative Divorce',
  'Estate Planning',
  'Elder Law',
  'Criminal Defense',
  'Personal Injury',
  'Business Law',
  'Real Estate Law',
]

